"""Database constraints, tested against PostgreSQL directly.

Every insert here goes through SQL, not through the API. That is deliberate: the
question is not whether a router validates its payload — the pydantic schemas and
the router tests already answer that — but whether the invariant survives a writer
that never touches the router. Anything enforced only in Python would pass those
tests and fail these.

Assertions name the constraint that refused the write, or the SQLSTATE class when
the name is generated by PostgreSQL (a foreign key declared inline is named by the
server): 23505 unique, 23503 foreign key, 23502 not null, 23514 check.

Each violating statement is written so exactly one invariant can fire. A row that
broke a foreign key *and* a check would make the assertion a coin toss.
"""
from __future__ import annotations

import pytest
from sqlalchemy.exc import IntegrityError, ProgrammingError

from app.models import (
    Assignment,
    AuditLog,
    DuplicateReview,
    Prize,
    Score,
    ScoreCriterion,
    Submission,
    Team,
    TeamMember,
    Track,
    User,
)

pytestmark = pytest.mark.postgres

FOREIGN_KEY_VIOLATION = "23503"
NOT_NULL_VIOLATION = "23502"

INSERT_USER = "INSERT INTO users (email, name, role) VALUES (:email, :name, :role)"


@pytest.fixture()
def graph(db, make_user):
    """One row of every kind, so a violation test has a valid world to break."""
    organizer = make_user("admin", email="organizer@constraints.test")
    judge = make_user("judge", email="judge@constraints.test")
    participant = make_user("participant", email="hacker@constraints.test")

    team = Team(name="Constraint Team", invite_code="CONSTRAIN", created_by=participant.id)
    db.add(team)
    db.flush()
    db.add(TeamMember(team_id=team.id, user_id=participant.id))

    track = Track(name="Constraint Track", slug="constraint-track")
    db.add(track)
    db.flush()
    db.add(Prize(track_id=track.id, rank=1, title="Best Constraint"))

    submission = Submission(
        team_id=team.id,
        title="Constraint Project",
        repo_url="https://github.com/constraints/project",
        track_id=track.id,
        status="submitted",
    )
    db.add(submission)
    db.flush()

    assignment = Assignment(judge_id=judge.id, submission_id=submission.id)
    score = Score(submission_id=submission.id, judge_id=judge.id, technical_score=7)
    db.add_all([assignment, score])
    db.flush()
    db.add(ScoreCriterion(score_id=score.id, key="code", label="Code", weight=100.0, value=7))
    db.commit()

    return {
        "organizer": organizer,
        "judge": judge,
        "participant": participant,
        "team": team,
        "track": track,
        "submission": submission,
        "assignment": assignment,
        "score": score,
    }


# ── uniqueness ───────────────────────────────────────────────────────────────


def test_a_duplicate_email_is_refused(expect_violation, graph):
    with expect_violation(
        INSERT_USER,
        {"email": "hacker@constraints.test", "name": "Dup", "role": "participant"},
        "uq_users_email",
    ):
        pass


def test_a_duplicate_github_id_is_refused(raw, expect_violation, graph):
    raw(
        "INSERT INTO users (email, name, role, github_id) VALUES ('one@gh.test', 'One', 'participant', 'gh-1')"
    )
    with expect_violation(
        "INSERT INTO users (email, name, role, github_id) "
        "VALUES ('two@gh.test', 'Two', 'participant', 'gh-1')",
        None,
        "uq_users_github_id",
    ):
        pass


def test_many_users_may_have_no_github_id(raw, query, graph):
    """The unique index must not turn "no GitHub account" into a collision."""
    raw("INSERT INTO users (email, name, role) VALUES ('nogh1@test.dev', 'A', 'participant')")
    raw("INSERT INTO users (email, name, role) VALUES ('nogh2@test.dev', 'B', 'participant')")
    assert query("SELECT count(*) FROM users WHERE github_id IS NULL")[0][0] == 5


def test_two_teams_cannot_share_a_name(expect_violation, graph):
    with expect_violation(
        "INSERT INTO teams (name, invite_code) VALUES ('Constraint Team', 'OTHER001')",
        None,
        "uq_teams_name",
    ):
        pass


def test_two_teams_cannot_share_an_invite_code(expect_violation, graph):
    with expect_violation(
        "INSERT INTO teams (name, invite_code) VALUES ('Other Team', 'CONSTRAIN')",
        None,
        "uq_teams_invite_code",
    ):
        pass


def test_a_user_cannot_be_on_two_teams(raw, query, expect_violation, graph):
    raw("INSERT INTO teams (name, invite_code) VALUES ('Second Team', 'SECOND02')")
    second = query("SELECT id FROM teams WHERE name = 'Second Team'")[0][0]
    with expect_violation(
        "INSERT INTO team_members (team_id, user_id) VALUES (:team_id, :user_id)",
        {"team_id": second, "user_id": graph["participant"].id},
        "uq_team_members_user",
    ):
        pass


def test_a_team_can_have_only_one_submission(expect_violation, graph):
    with expect_violation(
        "INSERT INTO submissions (team_id, title, repo_url) "
        "VALUES (:team_id, 'Second', 'https://github.com/c/second')",
        {"team_id": graph["team"].id},
        "uq_submissions_team",
    ):
        pass


def test_a_judge_cannot_be_assigned_twice_to_the_same_project(expect_violation, graph):
    with expect_violation(
        "INSERT INTO assignments (judge_id, submission_id) VALUES (:judge_id, :submission_id)",
        {"judge_id": graph["judge"].id, "submission_id": graph["submission"].id},
        "uq_assignment_pair",
    ):
        pass


def test_two_judges_can_be_assigned_to_the_same_project(db, raw, graph, make_user):
    second = make_user("judge", email="judge2@constraints.test")
    raw(
        "INSERT INTO assignments (judge_id, submission_id) VALUES (:judge_id, :submission_id)",
        {"judge_id": second.id, "submission_id": graph["submission"].id},
    )
    assert db.query(Assignment).filter_by(submission_id=graph["submission"].id).count() == 2


def test_a_judge_files_one_score_row_per_project(expect_violation, graph):
    with expect_violation(
        "INSERT INTO scores (submission_id, judge_id, technical_score) "
        "VALUES (:submission_id, :judge_id, 9)",
        {"submission_id": graph["submission"].id, "judge_id": graph["judge"].id},
        "uq_score_pair",
    ):
        pass


def test_a_verdict_cannot_repeat_a_rubric_criterion(expect_violation, graph):
    with expect_violation(
        "INSERT INTO score_criteria (score_id, key, value) VALUES (:score_id, 'code', 5)",
        {"score_id": graph["score"].id},
        "uq_score_criterion_key",
    ):
        pass


def test_track_names_and_slugs_are_unique(expect_violation, graph):
    with expect_violation(
        "INSERT INTO tracks (name, slug) VALUES ('Constraint Track', 'other-slug')",
        None,
        "uq_tracks_name",
    ):
        pass
    with expect_violation(
        "INSERT INTO tracks (name, slug) VALUES ('Other Track', 'constraint-track')",
        None,
        "uq_tracks_slug",
    ):
        pass


def test_a_duplicate_pair_can_only_be_reviewed_once(raw, query, expect_violation, graph):
    raw("INSERT INTO teams (name, invite_code) VALUES ('Dup Team', 'DUP00001')")
    team_id = query("SELECT id FROM teams WHERE name = 'Dup Team'")[0][0]
    raw(
        "INSERT INTO submissions (team_id, title, repo_url) "
        "VALUES (:team_id, 'Duplicate Project', 'https://github.com/c/dup')",
        {"team_id": team_id},
    )
    duplicate_id = query("SELECT id FROM submissions WHERE title = 'Duplicate Project'")[0][0]
    raw(
        "INSERT INTO duplicate_reviews (submission_id, duplicate_of_submission_id, decision) "
        "VALUES (:duplicate, :original, 'duplicate')",
        {"duplicate": duplicate_id, "original": graph["submission"].id},
    )
    with expect_violation(
        "INSERT INTO duplicate_reviews (submission_id, duplicate_of_submission_id, decision) "
        "VALUES (:duplicate, :original, 'duplicate')",
        {"duplicate": duplicate_id, "original": graph["submission"].id},
        "uq_duplicate_pair",
    ):
        pass


# ── foreign keys and invalid references ──────────────────────────────────────


def test_a_submission_cannot_reference_a_missing_team(expect_violation, sqlstate):
    with expect_violation(
        "INSERT INTO submissions (team_id, title, repo_url) "
        "VALUES (999999, 'Ghost', 'https://github.com/g/ghost')"
    ) as exc:
        pass
    assert sqlstate(exc) == FOREIGN_KEY_VIOLATION


def test_a_submission_cannot_reference_a_missing_track(expect_violation, sqlstate, graph):
    with expect_violation(
        "UPDATE submissions SET track_id = 999999 WHERE id = :id",
        {"id": graph["submission"].id},
    ) as exc:
        pass
    assert sqlstate(exc) == FOREIGN_KEY_VIOLATION


def test_an_assignment_cannot_reference_a_missing_judge(expect_violation, sqlstate, graph):
    with expect_violation(
        "INSERT INTO assignments (judge_id, submission_id) VALUES (999999, :submission_id)",
        {"submission_id": graph["submission"].id},
    ) as exc:
        pass
    assert sqlstate(exc) == FOREIGN_KEY_VIOLATION


def test_a_score_cannot_reference_a_missing_submission(expect_violation, sqlstate, graph):
    with expect_violation(
        "INSERT INTO scores (submission_id, judge_id, technical_score) "
        "VALUES (999999, :judge_id, 6)",
        {"judge_id": graph["judge"].id},
    ) as exc:
        pass
    assert sqlstate(exc) == FOREIGN_KEY_VIOLATION


def test_a_criterion_cannot_reference_a_missing_verdict(expect_violation, sqlstate):
    with expect_violation(
        "INSERT INTO score_criteria (score_id, key, value) VALUES (999999, 'ghost', 5)"
    ) as exc:
        pass
    assert sqlstate(exc) == FOREIGN_KEY_VIOLATION


def test_a_prize_cannot_reference_a_missing_track(expect_violation, sqlstate):
    with expect_violation(
        "INSERT INTO prizes (track_id, rank, title) VALUES (999999, 1, 'Ghost Prize')"
    ) as exc:
        pass
    assert sqlstate(exc) == FOREIGN_KEY_VIOLATION


# ── required fields ──────────────────────────────────────────────────────────


@pytest.mark.parametrize(
    "statement, params, field",
    [
        ("INSERT INTO users (email, name, role) VALUES (NULL, 'X', 'participant')", {}, "users.email"),
        ("INSERT INTO teams (name, invite_code) VALUES (NULL, 'NULL0001')", {}, "teams.name"),
        ("INSERT INTO teams (name, invite_code) VALUES ('No Code', NULL)", {}, "teams.invite_code"),
        (
            "INSERT INTO submissions (team_id, title, repo_url) "
            "VALUES ((SELECT max(id) FROM teams), NULL, 'https://github.com/n/t')",
            {},
            "submissions.title",
        ),
        (
            "INSERT INTO submissions (team_id, title, repo_url) "
            "VALUES ((SELECT max(id) FROM teams), 'No Repo', NULL)",
            {},
            "submissions.repo_url",
        ),
        (
            "INSERT INTO scores (submission_id, judge_id, technical_score) "
            "VALUES ((SELECT id FROM submissions LIMIT 1), NULL, 7)",
            {},
            "scores.judge_id",
        ),
        (
            "INSERT INTO score_criteria (score_id, key, value) "
            "VALUES ((SELECT id FROM scores LIMIT 1), NULL, 5)",
            {},
            "score_criteria.key",
        ),
        (
            "INSERT INTO score_criteria (score_id, key, value) "
            "VALUES ((SELECT id FROM scores LIMIT 1), 'k', NULL)",
            {},
            "score_criteria.value",
        ),
        ("INSERT INTO audit_logs (action) VALUES (NULL)", {}, "audit_logs.action"),
        ("INSERT INTO import_batches (source) VALUES (NULL)", {}, "import_batches.source"),
    ],
)
def test_required_fields_are_enforced_by_the_database(
    raw, expect_violation, sqlstate, graph, statement, params, field
):
    # A fresh team for the submission rows: the team in `graph` already has a
    # project, and a unique violation would answer a different question.
    raw("INSERT INTO teams (name, invite_code) VALUES ('Required Fields Team', 'REQFIELD')")
    with expect_violation(statement, params) as exc:
        pass
    assert sqlstate(exc) == NOT_NULL_VIOLATION, f"{field} accepted NULL"


# ── value domains (migration 0004) ───────────────────────────────────────────


def test_the_role_domain_is_enforced_by_the_database(expect_violation, graph):
    with expect_violation(
        INSERT_USER,
        {"email": "organiser@constraints.test", "name": "Wrong", "role": "organizer"},
        "ck_users_role",
    ):
        pass


def test_the_submission_status_domain_is_enforced_by_the_database(raw, query, expect_violation, graph):
    raw("INSERT INTO teams (name, invite_code) VALUES ('Status Team', 'STATUS01')")
    team_id = query("SELECT id FROM teams WHERE name = 'Status Team'")[0][0]
    with expect_violation(
        "INSERT INTO submissions (team_id, title, repo_url, status) "
        "VALUES (:team_id, 'Bad status', 'https://github.com/c/bad', 'archived')",
        {"team_id": team_id},
        "ck_submissions_status",
    ):
        pass
    # and on an existing row, where the invariant matters most
    with expect_violation(
        "UPDATE submissions SET status = 'archived' WHERE id = :id",
        {"id": graph["submission"].id},
        "ck_submissions_status",
    ):
        pass


@pytest.mark.parametrize(
    "column, value, constraint",
    [
        ("technical_score", 0, "ck_scores_technical_range"),
        ("technical_score", 11, "ck_scores_technical_range"),
        ("presentation_score", 0, "ck_scores_presentation_range"),
        ("presentation_score", 12, "ck_scores_presentation_range"),
    ],
)
def test_a_verdict_outside_one_to_ten_is_refused(
    expect_violation, graph, make_user, column, value, constraint
):
    # A second judge on the same project: valid foreign keys, no unique clash, so
    # the only rule that can refuse this row is the range check.
    second = make_user("judge", email=f"range-{column}-{value}@constraints.test")
    with expect_violation(
        f"INSERT INTO scores (submission_id, judge_id, {column}) VALUES (:submission_id, :judge_id, :value)",
        {"submission_id": graph["submission"].id, "judge_id": second.id, "value": value},
        constraint,
    ):
        pass


def test_a_criterion_value_outside_one_to_ten_is_refused(expect_violation, graph):
    with expect_violation(
        "INSERT INTO score_criteria (score_id, key, value) VALUES (:score_id, 'range', 0)",
        {"score_id": graph["score"].id},
        "ck_score_criteria_value_range",
    ):
        pass


def test_an_impossible_integrity_percentage_is_refused(expect_violation, graph):
    with expect_violation(
        "UPDATE submissions SET integrity_pct_in_window = 140 WHERE id = :id",
        {"id": graph["submission"].id},
        "ck_submissions_integrity_pct",
    ):
        pass
    with expect_violation(
        "UPDATE submissions SET integrity_pct_in_window = -0.5 WHERE id = :id",
        {"id": graph["submission"].id},
        "ck_submissions_integrity_pct",
    ):
        pass


def test_the_boundary_values_the_api_allows_are_allowed(raw, db, graph):
    """A check that also rejects the documented edge is a bug, not a guard."""
    raw(
        "UPDATE submissions SET integrity_pct_in_window = 0 WHERE id = :id",
        {"id": graph["submission"].id},
    )
    raw(
        "UPDATE submissions SET integrity_pct_in_window = 100 WHERE id = :id",
        {"id": graph["submission"].id},
    )
    raw(
        "UPDATE scores SET technical_score = 1, presentation_score = 10 WHERE id = :id",
        {"id": graph["score"].id},
    )
    db.expire_all()
    assert db.get(Score, graph["score"].id).presentation_score == 10


# ── delete rules ─────────────────────────────────────────────────────────────


def test_deleting_a_team_removes_its_project_verdicts_and_assignments(raw, query, graph):
    raw("DELETE FROM teams WHERE id = :id", {"id": graph["team"].id})

    assert query("SELECT count(*) FROM submissions")[0][0] == 0
    assert query("SELECT count(*) FROM assignments")[0][0] == 0
    assert query("SELECT count(*) FROM scores")[0][0] == 0
    assert query("SELECT count(*) FROM score_criteria")[0][0] == 0


def test_deleting_a_track_keeps_the_project_and_unscopes_its_prizes(raw, query, graph):
    """`ondelete="SET NULL"`, not CASCADE: deleting a category must not delete work."""
    raw("DELETE FROM tracks WHERE id = :id", {"id": graph["track"].id})

    assert query("SELECT id, track_id FROM submissions") == [(graph["submission"].id, None)]
    assert query("SELECT track_id FROM prizes") == [(None,)]


def test_deleting_a_judge_leaves_the_audit_trail_intact(
    raw, query, graph, mark_audit_entries
):
    """Verdicts are personal data; the audit trail is the record of what happened.

    Deleting the judge removes their verdicts (CASCADE). The trail is not touched
    at all: `actor_id` is the id the judge had when the entry was written and
    `actor_email` is the durable attribution, so history survives verbatim. That is
    the point of migration 0005 — with `ON DELETE SET NULL` still in place,
    PostgreSQL tried to anonymise the row, the append-only trigger refused the
    UPDATE, and the delete itself failed.
    """
    marker = mark_audit_entries()
    raw(
        "INSERT INTO audit_logs (actor_id, actor_email, action, entity) "
        "VALUES (:actor_id, :email, 'score.technical_submitted', 'score')",
        {"actor_id": graph["judge"].id, "email": graph["judge"].email},
    )

    raw("DELETE FROM users WHERE id = :id", {"id": graph["judge"].id})

    assert query("SELECT count(*) FROM scores WHERE judge_id = :id", {"id": graph["judge"].id})[0][0] == 0
    rows = query(
        "SELECT actor_id, actor_email, action FROM audit_logs WHERE id > :marker",
        {"marker": marker},
    )
    assert rows == [
        (graph["judge"].id, graph["judge"].email, "score.technical_submitted")
    ]


def test_deleting_a_submission_cascades_to_its_duplicate_review(raw, query, graph):
    raw("INSERT INTO teams (name, invite_code) VALUES ('Dup Cascade', 'DUPCASC1')")
    team_id = query("SELECT id FROM teams WHERE name = 'Dup Cascade'")[0][0]
    raw(
        "INSERT INTO submissions (team_id, title, repo_url) "
        "VALUES (:team_id, 'Dup Cascade Project', 'https://github.com/c/dupc')",
        {"team_id": team_id},
    )
    other = query("SELECT id FROM submissions WHERE title = 'Dup Cascade Project'")[0][0]
    raw(
        "INSERT INTO duplicate_reviews (submission_id, duplicate_of_submission_id) "
        "VALUES (:other, :original)",
        {"other": other, "original": graph["submission"].id},
    )

    raw("DELETE FROM submissions WHERE id = :id", {"id": other})

    assert query("SELECT count(*) FROM duplicate_reviews")[0][0] == 0
    assert query("SELECT count(*) FROM submissions")[0][0] == 1


# ── the writers the application actually uses ─────────────────────────────────


def test_the_orm_cannot_bypass_a_constraint_either(db, graph, constraint_name):
    """The API's writer is SQLAlchemy; a constraint has to hold for it too."""
    db.add(Team(name="Constraint Team", invite_code="ORM00001"))
    with pytest.raises(IntegrityError) as info:
        db.commit()
    db.rollback()
    assert constraint_name(info.value) == "uq_teams_name"


def test_an_audit_entry_written_through_the_orm_is_append_only(db, graph):
    entry = AuditLog(action="constraints.probe", actor_id=graph["organizer"].id)
    db.add(entry)
    db.commit()
    entry_id = entry.id

    entry.action = "constraints.rewritten"
    # The trigger raises, so this is a database error rather than a constraint
    # violation: `IntegrityError` would mean a uniqueness or foreign-key rule.
    with pytest.raises(ProgrammingError) as info:
        db.commit()
    db.rollback()
    assert "append-only" in str(info.value), "the trigger, not the API, refused this"

    db.expire_all()
    assert db.get(AuditLog, entry_id).action == "constraints.probe"


def test_duplicate_review_through_the_orm_is_refused(db, graph, constraint_name):
    other_team = Team(name="ORM Dup Team", invite_code="ORMDUP01")
    db.add(other_team)
    db.flush()
    other = Submission(
        team_id=other_team.id,
        title="ORM Duplicate",
        repo_url="https://github.com/orm/duplicate",
        status="submitted",
    )
    db.add(other)
    db.flush()
    db.add(DuplicateReview(submission_id=other.id, duplicate_of_submission_id=graph["submission"].id))
    db.commit()

    db.add(DuplicateReview(submission_id=other.id, duplicate_of_submission_id=graph["submission"].id))
    with pytest.raises(IntegrityError) as info:
        db.commit()
    db.rollback()
    assert constraint_name(info.value) == "uq_duplicate_pair"


def test_registration_through_the_api_still_satisfies_the_role_check(client, db):
    """A guard is only useful if the real writer keeps satisfying it."""
    response = client.post(
        "/api/auth/register",
        json={"email": "rolecheck@test.dev", "password": "password123", "name": "Role Check"},
    )
    assert response.status_code == 200, response.text
    assert db.query(User).filter_by(email="rolecheck@test.dev").count() == 1


def test_email_uniqueness_is_case_sensitive_in_the_database(raw, query, graph):
    """The database compares exactly; the API is what folds case.

    `schemas.RegisterRequest` lowercases the address before it reaches SQLAlchemy,
    so the API cannot create `A@x.dev` next to `a@x.dev`. A bulk import that
    bypasses the schema could — a duplicate-looking roster is therefore something
    an importer has to normalise itself rather than something the index prevents.
    """
    raw(INSERT_USER, {"email": "Case@test.dev", "name": "Upper", "role": "participant"})
    raw(INSERT_USER, {"email": "case@test.dev", "name": "Lower", "role": "participant"})
    assert query("SELECT count(*) FROM users WHERE lower(email) = 'case@test.dev'")[0][0] == 2
