"""Fixture import: load a messy real-world dataset, diagnose it, apply it.

Real events arrive with problems, and a platform that only copes with a curated
demo is not a platform. This module is built for the cases that actually hurt:

  * **incomplete review batches** — assignments with no verdict. A missing score
    is *missing*, never zero, and coverage is reported rather than assumed;
  * **a zero-variance judge** (every verdict identical) and a **single-verdict
    judge** — the two degenerate cases `zscore` guards against. Both are
    *detected from the data*, not read from a note in the file, so the detector
    can be checked independently of the dataset's own claims;
  * **duplicate submissions** — detected by comparing normalised repository URLs
    and title fingerprints. Detection is deterministic and recomputed on demand;
    only an organiser's decision is persisted (`duplicate_reviews`);
  * **missing comments and summaries** — nulls stay null all the way through;
  * **string identifiers** — every imported row keeps its source key in
    `source_ref`, so an import is idempotent and traceable;
  * **a closed event window** — imported deadlines are respected, never
    "helpfully" reopened.

The fixture file is Axion's own (`fixtures.json`, generated by
`api/scripts/build_fixtures.py`). No organiser-provided fixture set existed when
this was built, and nothing here pretends otherwise.
"""
from __future__ import annotations

import json
import re
import zlib
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable, Optional

from sqlalchemy import select
from sqlalchemy.orm import Session

from .audit import record
from .models import (
    Assignment,
    ImportBatch,
    Prize,
    Rubric,
    Score,
    ScoreCriterion,
    Submission,
    Team,
    TeamMember,
    Track,
    User,
)
from .security import hash_password
from .services import DEFAULT_RUBRIC_NAME, ensure_default_rubric
from .timeutil import iso

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_FIXTURE_PATH = REPO_ROOT / "fixtures.json"

FIXTURE_SOURCE = "fixtures.json"
RUBRIC_FALLBACK_MIN_COVERAGE = 3


# ── loading and normalisation ────────────────────────────────────────────────


def load_fixture(path: Path | str | None = None) -> dict[str, Any]:
    """Read a fixture file. Raises ValueError if it is not a usable dataset."""
    resolved = Path(path) if path else DEFAULT_FIXTURE_PATH
    if not resolved.is_absolute():
        resolved = REPO_ROOT / resolved
    if not resolved.exists():
        raise ValueError(f"fixture file not found: {resolved}")
    try:
        payload = json.loads(resolved.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"{resolved.name} is not valid JSON: {exc}") from exc
    if not isinstance(payload, dict):
        raise ValueError(f"{resolved.name} must contain a JSON object")
    if not payload.get("projects"):
        raise ValueError(f"{resolved.name} contains no projects")
    return payload


def parse_utc(value: Any) -> Optional[datetime]:
    """Parse an ISO-8601 timestamp and normalise it to UTC.

    Naive timestamps are treated as UTC rather than as local time: guessing a
    timezone would silently shift deadlines, which is the one thing a submission
    window cannot afford.
    """
    if value in (None, ""):
        return None
    try:
        parsed = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return None
    if parsed.tzinfo is None:
        return parsed.replace(tzinfo=timezone.utc)
    return parsed.astimezone(timezone.utc)


def normalize_repo_url(value: Any) -> str:
    """A comparison key for a repository URL: scheme, casing, `.git`, trailing slash."""
    text = str(value or "").strip().lower()
    if "://" in text:
        text = text.split("://", 1)[1]
    text = text.split("?", 1)[0].split("#", 1)[0]
    if text.startswith("www."):
        text = text[4:]
    text = text.rstrip("/")
    if text.endswith(".git"):
        text = text[: -len(".git")]
    return re.sub(r"\s+", "", text)


def title_fingerprint(value: Any) -> str:
    """A comparison key for a title, ignoring bracketed suffixes and punctuation.

    "Nimbus Mesh (final v2)" and "nimbus mesh" share a fingerprint; "Mesh
    Scheduler" and "Mesh Relay" do not, which is the point — a shared word is not
    a duplicate.
    """
    text = re.sub(r"\([^)]*\)", " ", str(value or "").lower())
    return re.sub(r"[^a-z0-9]+", "", text)


# ── validation ───────────────────────────────────────────────────────────────


def validate(fixture: dict[str, Any]) -> list[dict[str, Any]]:
    """Structural problems that would make an import unsafe. Empty is healthy."""
    problems: list[dict[str, Any]] = []

    def problem(kind: str, ref: str, detail: str) -> None:
        problems.append({"kind": kind, "ref": ref, "detail": detail})

    projects = list(fixture.get("projects") or [])
    judges = list(fixture.get("judges") or [])
    teams = {team.get("id") for team in fixture.get("teams") or []}
    tracks = {track.get("id") for track in fixture.get("tracks") or []}
    judge_ids = {judge.get("id") for judge in judges}
    project_ids = {project.get("id") for project in projects}

    for label, rows in (("project", projects), ("judge", judges)):
        seen: set[str] = set()
        for row in rows:
            ref = str(row.get("id"))
            if not ref or ref == "None":
                problem("missing_id", label, "a record has no id")
                continue
            if ref in seen:
                problem("duplicate_id", ref, f"two {label}s share this id")
            seen.add(ref)

    # Only people need an email address; a project row does not have one, and
    # flagging every project for it would bury the real problems in noise.
    for label, rows in (
        ("judge", judges),
        ("participant", fixture.get("participants") or []),
    ):
        for row in rows:
            if not str(row.get("email") or "").strip():
                problem(
                    "missing_email",
                    str(row.get("id")),
                    f"a {label} has no email address to sign in with",
                )

    for project in projects:
        ref = str(project.get("id"))
        if not str(project.get("title") or "").strip():
            problem("missing_title", ref, "the project has no title")
        if not str(project.get("repo_url") or "").strip():
            problem("missing_repo_url", ref, "the project has no repository URL")
        if project.get("team_id") not in teams:
            problem("unknown_team", ref, f"team {project.get('team_id')!r} is not declared")
        if project.get("track_id") and project.get("track_id") not in tracks:
            problem("unknown_track", ref, f"track {project.get('track_id')!r} is not declared")
        for field in ("submitted_at",):
            if project.get(field) and parse_utc(project[field]) is None:
                problem("bad_timestamp", ref, f"{field}={project[field]!r} is not ISO-8601")
        for judge_id in project.get("assigned_judges") or []:
            if judge_id not in judge_ids:
                problem("unknown_judge", ref, f"assigned judge {judge_id!r} is not declared")
        duplicate_of = project.get("declared_duplicate_of")
        if duplicate_of and duplicate_of not in project_ids:
            problem("unknown_duplicate", ref, f"declared duplicate of {duplicate_of!r}, which is absent")

    for review in fixture.get("reviews") or []:
        ref = f"{review.get('judge_id')}→{review.get('project_id')}"
        if review.get("project_id") not in project_ids:
            problem("unknown_project", ref, "the review references an undeclared project")
        if review.get("judge_id") not in judge_ids:
            problem("unknown_judge", ref, "the review references an undeclared judge")
        technical = review.get("technical")
        if technical is not None and not (1 <= int(technical) <= 10):
            problem("out_of_range", ref, f"technical score {technical!r} is outside 1–10")
        if review.get("submitted_at") and parse_utc(review["submitted_at"]) is None:
            problem("bad_timestamp", ref, "submitted_at is not ISO-8601")

    return problems


# ── duplicate detection ──────────────────────────────────────────────────────


def _id_sort_key(row: dict[str, Any]) -> tuple[int, int, str]:
    """Sort ids naturally: `7` is project seven, and it comes before project 31.

    A plain string sort puts "31" before "7", which quietly nominated the wrong
    submission as the canonical one of a duplicate pair.
    """
    reference = str(row.get("id"))
    if reference.isdigit():
        return (0, int(reference), "")
    return (1, 0, reference)


def duplicate_candidates(projects: Iterable[dict[str, Any]]) -> list[dict[str, Any]]:
    """Deterministic duplicate detection over a list of project dicts.

    Two projects are candidates when their repository URLs match after
    normalisation, or when their title fingerprints match. The lowest id in a
    group is treated as the canonical submission.
    """
    rows = [project for project in projects if project.get("id")]
    by_repo: dict[str, list[dict[str, Any]]] = defaultdict(list)
    by_title: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for project in rows:
        key = normalize_repo_url(project.get("repo_url"))
        if key:
            by_repo[key].append(project)
        fingerprint = title_fingerprint(project.get("title"))
        if fingerprint:
            by_title[fingerprint].append(project)

    found: dict[tuple[str, str], dict[str, Any]] = {}

    def add(canonical: dict[str, Any], other: dict[str, Any], reason: str) -> None:
        key = (str(canonical["id"]), str(other["id"]))
        if key in found:
            return
        found[key] = {
            "submission": other["id"],
            "duplicate_of": canonical["id"],
            "reason": reason,
        }

    for key, group in by_repo.items():
        if len(group) < 2:
            continue
        ordered = sorted(group, key=_id_sort_key)
        for other in ordered[1:]:
            add(ordered[0], other, f"same repository after normalisation ({key})")

    for key, group in by_title.items():
        if len(group) < 2:
            continue
        ordered = sorted(group, key=_id_sort_key)
        for other in ordered[1:]:
            add(ordered[0], other, f"same project title after normalisation ({key})")

    return sorted(found.values(), key=lambda row: (_id_sort_key(row), _id_sort_key({"id": row["submission"]})))


# ── diagnostics ──────────────────────────────────────────────────────────────


def diagnose(fixture: dict[str, Any]) -> dict[str, Any]:
    """Everything an organiser should know before trusting an import.

    Pure: no database, no side effects, so the diagnostics screen and the import
    report can never disagree about the same file.
    """
    projects = list(fixture.get("projects") or [])
    judges = list(fixture.get("judges") or [])
    reviews = list(fixture.get("reviews") or [])
    participants = list(fixture.get("participants") or [])
    teams = list(fixture.get("teams") or [])
    minimum = int(fixture.get("minimum_coverage") or RUBRIC_FALLBACK_MIN_COVERAGE)

    project_ids = [str(project.get("id")) for project in projects]
    review_counts = Counter(str(review.get("project_id")) for review in reviews)
    verdicts_by_judge = Counter(str(review.get("judge_id")) for review in reviews)

    assignments = sum(len(project.get("assigned_judges") or []) for project in projects)
    invalid = validate(fixture)

    zero_variance = sorted(
        str(judge.get("id"))
        for judge in judges
        if verdicts_by_judge[str(judge.get("id"))] > 1
        and len(
            {
                review.get("technical")
                for review in reviews
                if str(review.get("judge_id")) == str(judge.get("id"))
            }
        )
        == 1
    )
    single_verdict = sorted(
        str(judge.get("id"))
        for judge in judges
        if verdicts_by_judge[str(judge.get("id"))] == 1
    )
    without_reviews = sorted(ref for ref in project_ids if review_counts.get(ref, 0) == 0)
    below_minimum = [
        {
            "project": ref,
            "reviews": review_counts.get(ref, 0),
            "expected": minimum,
            "assigned": next(
                (
                    len(project.get("assigned_judges") or [])
                    for project in projects
                    if str(project.get("id")) == ref
                ),
                0,
            ),
        }
        for ref in project_ids
        if 0 < review_counts.get(ref, 0) < minimum
    ]
    candidates = duplicate_candidates(projects)
    declared = sum(1 for project in projects if project.get("declared_duplicate_of"))
    timestamps = [
        project.get("submitted_at") for project in projects if project.get("submitted_at")
    ] + [review.get("submitted_at") for review in reviews if review.get("submitted_at")]
    parsed = [parse_utc(value) for value in timestamps]
    event_end = parse_utc((fixture.get("event") or {}).get("ends_at"))
    string_ids = sum(
        1
        for row in [*projects, *judges, *teams]
        if isinstance(row.get("id"), str) and not str(row.get("id")).isdigit()
    )

    headline = [
        f"{len(projects)} projects imported",
        f"{len(judges)} judges imported",
        f"{len(below_minimum)} incomplete review batches detected"
        + (f" ({len(without_reviews)} with no verdicts at all)" if without_reviews else ""),
        f"{len(candidates)} duplicate candidate{'s' if len(candidates) != 1 else ''} detected",
        f"{len(zero_variance)} zero-variance judge{'s' if len(zero_variance) != 1 else ''} detected",
        f"{len(invalid)} invalid record{'s' if len(invalid) != 1 else ''}",
    ]

    return {
        "source": fixture.get("generator") or FIXTURE_SOURCE,
        "fixture_version": fixture.get("fixture_version"),
        "note": fixture.get("note"),
        "records": {
            "projects": len(projects),
            "judges": len(judges),
            "teams": len(teams),
            "participants": len(participants),
            "reviews": len(reviews),
            "assignments": assignments,
        },
        "headline": headline,
        "invalid": invalid,
        "duplicate_candidates": candidates,
        "duplicates_declared_in_file": declared,
        "duplicates_detected": len(candidates),
        "zero_variance_judges": zero_variance,
        "single_verdict_judges": single_verdict,
        "incomplete_batches": below_minimum,
        "projects_without_reviews": without_reviews,
        "minimum_coverage": minimum,
        "assignments_without_scores": max(assignments - len(reviews), 0),
        "null_technical_comments": sum(
            1 for review in reviews if review.get("technical_comment") is None
        ),
        "null_summaries": sum(1 for project in projects if project.get("summary") is None),
        "string_ids_preserved": string_ids,
        "timestamps_normalised_to_utc": all(
            moment is not None and moment.tzinfo is not None for moment in parsed
        ),
        "event_window": {
            "starts_at": (fixture.get("event") or {}).get("starts_at"),
            "ends_at": (fixture.get("event") or {}).get("ends_at"),
            "closed": bool(event_end and event_end < datetime.now(timezone.utc)),
        },
    }


# ── applying a fixture ───────────────────────────────────────────────────────


def _upsert_user(
    db: Session,
    *,
    email: str,
    name: str,
    role: str,
    source_ref: Optional[str],
    password: Optional[str],
) -> User:
    user = db.scalar(select(User).where(User.email == email))
    if user is None:
        user = User(email=email, name=name, role=role)
        db.add(user)
    user.name = name or user.name
    user.role = role
    if source_ref:
        user.source_ref = source_ref
    if password:
        user.password_hash = hash_password(password)
    db.flush()
    return user


def apply_fixture(
    db: Session,
    fixture: dict[str, Any],
    *,
    actor: User | None = None,
    mode: str = "apply",
    source: str | None = None,
    commit: bool = True,
) -> dict[str, Any]:
    """Write a fixture into the database. Idempotent on `source_ref`.

    `mode="dry_run"` records the batch and returns the diagnostics without
    touching anything else — the default for the admin endpoint, because an
    import that silently rewrites an event is not a feature.
    """
    diagnostics = diagnose(fixture)
    source_name = source or fixture.get("generator") or FIXTURE_SOURCE

    if mode == "dry_run" or diagnostics["invalid"]:
        summary = {**diagnostics, "applied": None, "mode": "dry_run"}
        if mode == "apply" and diagnostics["invalid"]:
            summary["refused"] = "records failed validation; nothing was written"
        _record_batch(db, source_name, summary, fixture, actor, mode="dry_run", commit=commit)
        return summary

    accounts = fixture.get("accounts") or {}
    judge_password = (accounts.get("judge") or {}).get("password")
    participant_password = (accounts.get("participant") or {}).get("password")

    # ── organiser configuration: rubric, tracks, prizes ─────────────────────
    rubric_payload = fixture.get("rubric") or {}
    criteria = list(rubric_payload.get("criteria") or [])
    rubric_name = rubric_payload.get("name") or DEFAULT_RUBRIC_NAME
    rubric = db.scalar(select(Rubric).where(Rubric.name == rubric_name))
    if rubric is None:
        for other in db.scalars(select(Rubric).where(Rubric.is_active.is_(True))).all():
            other.is_active = False
        rubric = Rubric(name=rubric_name, criteria=criteria, is_active=True)
        db.add(rubric)
        db.flush()
    else:
        rubric.criteria = criteria
        rubric.is_active = True
    ensure_default_rubric(db)

    track_rows: dict[str, Track] = {}
    for entry in fixture.get("tracks") or []:
        track = db.scalar(select(Track).where(Track.slug == entry.get("slug")))
        if track is None:
            track = Track(name=entry.get("name"), slug=entry.get("slug"))
            db.add(track)
        track.name = entry.get("name") or track.name
        track.description = entry.get("description") or track.description
        track.prize_pool = entry.get("prize_pool") or track.prize_pool
        db.flush()
        track_rows[str(entry.get("id"))] = track
        for prize in entry.get("prizes") or []:
            existing = db.scalar(
                select(Prize).where(
                    Prize.track_id == track.id, Prize.title == prize.get("title")
                )
            )
            if existing is None:
                db.add(
                    Prize(
                        track_id=track.id,
                        rank=int(prize.get("rank") or 1),
                        title=prize.get("title"),
                        description=prize.get("description"),
                    )
                )
    db.flush()

    # ── people ──────────────────────────────────────────────────────────────
    admin_account = accounts.get("admin") or {}
    if admin_account.get("email"):
        _upsert_user(
            db,
            email=admin_account["email"],
            name=admin_account.get("name") or "Fixture Organiser",
            role="admin",
            source_ref="admin",
            password=admin_account.get("password"),
        )

    judge_rows: dict[str, User] = {}
    for judge in fixture.get("judges") or []:
        if not judge.get("email"):
            continue  # validate() already reported it; nothing to write
        user = _upsert_user(
            db,
            email=judge.get("email"),
            name=judge.get("name") or "",
            role="judge",
            source_ref=str(judge.get("id")),
            password=judge_password,
        )
        judge_rows[str(judge.get("id"))] = user

    team_rows: dict[str, Team] = {}
    for index, team in enumerate(fixture.get("teams") or []):
        team_row = db.scalar(select(Team).where(Team.name == team.get("name")))
        if team_row is None:
            # crc32, not hash(): hash() is randomised per process, and an invite
            # code that changes on every import is not a code at all.
            code_seed = zlib.crc32(str(team.get("id")).encode()) % 997
            team_row = Team(
                name=team.get("name"),
                invite_code=f"FIX{index + 1:02d}{code_seed:03d}",
            )
            db.add(team_row)
        db.flush()
        team_rows[str(team.get("id"))] = team_row

    participant_rows: dict[str, User] = {}
    for participant in fixture.get("participants") or []:
        if not participant.get("email"):
            continue
        user = _upsert_user(
            db,
            email=participant.get("email"),
            name=participant.get("name") or "",
            role="participant",
            source_ref=str(participant.get("id")),
            password=participant_password,
        )
        participant_rows[str(participant.get("id"))] = user
        team_id = participant.get("team_id")
        if not team_id or str(team_id) not in team_rows:
            continue
        team_row = team_rows[str(team_id)]
        membership = db.scalar(
            select(TeamMember).where(TeamMember.user_id == user.id)
        )
        if membership is None:
            db.add(TeamMember(team_id=team_row.id, user_id=user.id))
        else:
            membership.team_id = team_row.id
        if team_row.created_by is None:
            team_row.created_by = user.id
    db.flush()

    # ── projects ────────────────────────────────────────────────────────────
    created_projects = 0
    updated_projects = 0
    submission_rows: dict[str, Submission] = {}
    for project in fixture.get("projects") or []:
        ref = str(project.get("id"))
        team_id = team_rows.get(str(project.get("team_id")))
        if team_id is None:
            continue
        submission = db.scalar(select(Submission).where(Submission.source_ref == ref))
        if submission is None:
            submission = db.scalar(select(Submission).where(Submission.team_id == team_id.id))
        if submission is None:
            submission = Submission(team_id=team_id.id, title=project.get("title"))
            db.add(submission)
            created_projects += 1
        else:
            updated_projects += 1

        integrity = project.get("commit_integrity") or {}
        track = track_rows.get(str(project.get("track_id")))
        submission.title = project.get("title") or submission.title
        submission.repo_url = project.get("repo_url") or submission.repo_url
        submission.docs_url = project.get("docs_url")
        submission.demo_url = project.get("demo_url")
        submission.video_url = project.get("video_url")
        submission.summary = project.get("summary")
        submission.track_id = track.id if track else submission.track_id
        submission.status = project.get("status") or "submitted"
        submission.submitted_at = parse_utc(project.get("submitted_at"))
        submission.source_ref = ref
        submission.integrity_pct_in_window = integrity.get("pct_in_window")
        submission.integrity_flagged = bool(integrity.get("flagged"))
        submission.integrity_source = "fixture"
        submission.integrity_details = {
            "source": "fixture",
            "pct_in_window": integrity.get("pct_in_window"),
            "flagged": bool(integrity.get("flagged")),
            "reason": "Imported from the fixture dataset." if integrity.get("flagged") else None,
        }
        submission.integrity_checked_at = datetime.now(timezone.utc)
        db.flush()
        submission_rows[ref] = submission

    # ── assignments and verdicts ────────────────────────────────────────────
    created_assignments = 0
    for project in fixture.get("projects") or []:
        submission = submission_rows.get(str(project.get("id")))
        if submission is None:
            continue
        for judge_ref in project.get("assigned_judges") or []:
            judge = judge_rows.get(str(judge_ref))
            if judge is None:
                continue
            existing = db.scalar(
                select(Assignment).where(
                    Assignment.judge_id == judge.id,
                    Assignment.submission_id == submission.id,
                )
            )
            if existing is None:
                db.add(Assignment(judge_id=judge.id, submission_id=submission.id))
                created_assignments += 1
    db.flush()

    created_scores = 0
    for review in fixture.get("reviews") or []:
        submission = submission_rows.get(str(review.get("project_id")))
        judge = judge_rows.get(str(review.get("judge_id")))
        if submission is None or judge is None:
            continue
        score = db.scalar(
            select(Score).where(
                Score.judge_id == judge.id, Score.submission_id == submission.id
            )
        )
        if score is None:
            score = Score(judge_id=judge.id, submission_id=submission.id)
            db.add(score)
            created_scores += 1
        technical = review.get("technical")
        presentation = review.get("presentation")
        submitted_at = parse_utc(review.get("submitted_at"))
        score.technical_score = int(technical) if technical is not None else None
        # A null comment stays null: "no comment given" is not the empty string.
        score.technical_comment = review.get("technical_comment")
        score.presentation_score = int(presentation) if presentation is not None else None
        score.presentation_comment = review.get("presentation_comment")
        score.technical_submitted_at = submitted_at if technical is not None else None
        score.presentation_submitted_at = submitted_at if presentation is not None else None
        score.rubric_id = rubric.id
        db.flush()

        if score.technical_score is not None:
            existing_criteria = {
                row.key: row
                for row in db.scalars(
                    select(ScoreCriterion).where(ScoreCriterion.score_id == score.id)
                ).all()
            }
            for entry in criteria:
                row = existing_criteria.pop(entry.get("key"), None)
                if row is None:
                    row = ScoreCriterion(score_id=score.id, key=entry.get("key"))
                    db.add(row)
                row.label = entry.get("label")
                row.weight = float(entry.get("weight") or 0.0)
                # Mirrors the derived technical verdict, exactly as the demo seed
                # does, so the Z-score contract is unchanged by importing.
                row.value = score.technical_score
            for orphan in existing_criteria.values():
                db.delete(orphan)
    db.flush()

    summary = {
        **diagnostics,
        "mode": "apply",
        "applied": {
            "projects_created": created_projects,
            "projects_updated": updated_projects,
            "judges": len(judge_rows),
            "teams": len(team_rows),
            "participants": len(participant_rows),
            "assignments_created": created_assignments,
            "scores_created": created_scores,
        },
        "refused": None,
    }
    _record_batch(db, source_name, summary, fixture, actor, mode="apply", commit=False)
    if actor is not None:
        record(
            db,
            "fixture.imported",
            actor=actor,
            entity="event",
            details={
                "source": source_name,
                "projects": diagnostics["records"]["projects"],
                "judges": diagnostics["records"]["judges"],
                "duplicates_detected": diagnostics["duplicates_detected"],
                "invalid": len(diagnostics["invalid"]),
            },
        )
    if commit:
        db.commit()
    return summary


def _record_batch(
    db: Session,
    source: str,
    summary: dict[str, Any],
    fixture: dict[str, Any],
    actor: User | None,
    *,
    mode: str,
    commit: bool,
) -> ImportBatch:
    batch = ImportBatch(
        source=source,
        mode=mode,
        fixture_version=fixture.get("fixture_version"),
        summary=summary,
        actor_id=actor.id if actor else None,
        actor_email=actor.email if actor else None,
    )
    db.add(batch)
    db.flush()
    if commit:
        db.commit()
    return batch


def latest_batch(db: Session) -> Optional[ImportBatch]:
    return db.scalar(select(ImportBatch).order_by(ImportBatch.id.desc()))


def batch_to_dict(batch: Optional[ImportBatch]) -> Optional[dict[str, Any]]:
    if batch is None:
        return None
    return {
        "id": batch.id,
        "source": batch.source,
        "mode": batch.mode,
        "fixture_version": batch.fixture_version,
        "summary": batch.summary,
        "actor_email": batch.actor_email,
        "created_at": iso(batch.created_at),
    }
